package com.ENAA_SUPPORT.Enum;

public enum PanneType {
    HARDWARE_FAILURE,
    SOFTWARE_ISSUE,
    NETWORK_PROBLEM,
    POWER_OUTAGE,
    OVERHEATING,
    SECURITY_BREACH,
    DATA_CORRUPTION,
    USER_ERROR,
    CONFIGURATION_ERROR,
    ENVIRONMENTAL_ISSUE;
}